#!/usr/bin/env sh
set -ex                   # Stop on first error and log all commands

CC="cc"
CFLAGS="-Wall -Wextra -Wshadow -Wmissing-declarations -Wswitch-enum -pedantic -std=c89"
LIBSSL="-lssl -lcrypto"

# Compile and run tests
$CC $CFLAGS -o gmiu.t   gmiu.t.c   && ./gmiu.t
$CC $CFLAGS -o gmip.t   gmip.t.c   && ./gmip.t
$CC $CFLAGS -o gmir.t   gmir.t.c   && ./gmir.t

# Compile programs
$CC $CFLAGS -o gmiu     gmiu.c
$CC $CFLAGS -o gmip     gmip.c
# -D_POSIX_C_SOURCE=200112L flag in compiler or this define below is
# necessary to programs that include netdb.h, that is programs that
# uses gmif.h because of problem with addrinfo struct of getaddrinfo.
# And ofc we need to include links to lib ssl.
$CC $CFLAGS -o gmif     gmif.c   $LIBSSL -D_POSIX_C_SOURCE=200112L
$CC $CFLAGS -o gmic     gmic.c   $LIBSSL -D_POSIX_C_SOURCE=200112L
