#!/bin/sh
set -xe

# -D_POSIX_C_SOURCE=200112L flag is added because of problem with
# addrinfo struct of getaddrinfo.  Solution to problem was taken from
# this disscussion:
# https://bytes.com/topic/c/answers/811663-problems-using-getaddrinfo-friends-using-c99-standard
cc -D_POSIX_C_SOURCE=200112L -Wall -Wextra -Wshadow -std=c89 -pedantic -o gmic main.c url.h -lssl -lcrypto
